use pulse_core::{ActorId, Value, Constant};
use pulse_core::object::{Object, Closure};
use pulse_vm::{VM, VMStatus};
use crate::mailbox::{Message, SystemMessage};
use std::collections::HashSet;
use tokio::sync::mpsc;
use crate::runtime::RuntimeHandle;

#[derive(Debug, PartialEq)]
pub enum ActorStatus {
    Starting,
    Running,
    Waiting,
    Terminated,
}

pub struct Actor {
    pub id: ActorId,
    pub vm: VM,
    pub links: HashSet<ActorId>,
    pub monitors: HashSet<ActorId>,
    pub trapping_exits: bool,
    pub runtime: RuntimeHandle, 
}

impl Actor {
    pub fn new(id: ActorId, vm: VM, runtime: RuntimeHandle) -> Self {
        Self {
            id,
            vm,
            links: HashSet::new(),
            monitors: HashSet::new(),
            trapping_exits: false,
            runtime, // Needed to spawn/send from within VM
        }
    }

    pub fn run(mut self, mut mailbox: mpsc::UnboundedReceiver<Message>) -> std::pin::Pin<Box<dyn std::future::Future<Output = ()> + Send>> {
        Box::pin(async move {
        loop {
            // Priority: Check mailbox first if we are in a "receivable" state?
            // Actually, we should run the VM. The VM returns Yield or Blocked.
            
            // Run for a time slice (steps)
            let status = self.vm.run(1000).await;
            
            match status {
                VMStatus::Running => {
                     // Should not happen with run(steps) unless steps > 0, but loop handles it.
                     tokio::task::yield_now().await;
                },
                VMStatus::Yielded => {
                    // Yielded generally means "give other tasks a chance" or "I did some I/O"
                    // Check mailbox for non-blocking messages?
                    // For now, just yield to tokio scheduler.
                    // But we should process system messages (kills, etc.)
                    while let Ok(msg) = mailbox.try_recv() {
                         self.handle_message(msg);
                    }
                    tokio::task::yield_now().await;
                },
                VMStatus::Blocked => {
                    // VM is waiting for a message (Receive instruction)
                    // We must await the mailbox.
                    if let Some(msg) = mailbox.recv().await {
                         self.handle_message(msg);
                    } else {
                        // Mailbox closed, runtime shutting down?
                        break;
                    }
                },
                VMStatus::Send { target, msg } => {
                    // Async send
                    let _ = self.runtime.send(target, Message::User(msg)).await;
                },
                VMStatus::Spawn(offset) => {
                    let chunk = self.vm.get_current_chunk();
                    // We need to spawn a new actor.
                    // The child PID is generated by Runtime.
                    let child_pid = self.runtime.spawn_from_actor(chunk, offset).await;
                    self.vm.push(Value::Pid(child_pid));
                },
                 VMStatus::SpawnLink(offset) => {
                     let chunk = self.vm.get_current_chunk();
                     let child_pid = self.runtime.spawn_from_actor(chunk, offset).await;
                     
                     // Link
                     self.links.insert(child_pid);
                     // We need to tell child to link back.
                     let _ = self.runtime.send(child_pid, Message::System(SystemMessage::Link(self.id))).await;
                     
                     self.vm.push(Value::Pid(child_pid));
                 },
                 VMStatus::Link(target) => {
                     self.links.insert(target);
                     // Notify target
                     let _ = self.runtime.send(target, Message::System(SystemMessage::Link(self.id))).await;
                 },
                 VMStatus::Monitor(target) => {
                     let _ = self.runtime.monitor(self.id, target).await;
                 },
                 VMStatus::Register(name, target) => {
                     let res = self.runtime.register(name, target).await;
                     self.vm.push(Value::Bool(res));
                 },
                 VMStatus::Unregister(name) => {
                     self.runtime.unregister(&name).await;
                     self.vm.push(Value::Unit);
                 },
                 VMStatus::WhereIs(name) => {
                     let pid = self.runtime.whereis(&name).await;
                     match pid {
                         Some(p) => self.vm.push(Value::Pid(p)),
                         None => self.vm.push(Value::Unit),
                     }
                 },
                 VMStatus::Import(_) => {
                     // TODO: Async import support
                     // For now, this might fail or need sync fallback
                     // The VM handles import internally mostly, but if it returns status,
                     // it means it needs runtime help.
                     // The previous runtime implementation did a lot here.
                     // We need to port that logic to async.
                     todo!("Async Import Implementation"); 
                 },
                 VMStatus::Halted => {
                     // Normal exit
                     self.runtime.exit(self.id, "normal".to_string()).await;
                     break;
                 },
                 VMStatus::Error(e) => {
                     self.runtime.exit(self.id, format!("{}", e)).await;
                     break;
                 }
                _ => {}
            }
            }
        })
    }

    fn handle_message(&mut self, msg: Message) {
         match msg {
             Message::User(constant) => {
                 // Convert Constant to Value and push to VM
                 let val = self.constant_to_value(constant);
                 self.vm.push(val);
             },
             Message::System(sys) => {
                 match sys {
                     SystemMessage::Link(pid) => {
                         self.links.insert(pid);
                     },
                     SystemMessage::Exit(_pid, _reason) => {
                         if self.trapping_exits {
                             // Convert to message
                              // push {'EXIT', pid, reason}
                         } else {
                             // Die
                             // We should probably trigger Error status or similar
                             // For now, simple termination
                            //  self.vm.status = ...?
                            // This usually happens in the loop.
                         }
                     },

                     SystemMessage::MonitorExit(_pid, _reason) => {
                         // Push {'DOWN', ...}
                     },
                     _ => {}
                 }
             }
         }
    }
    
    fn constant_to_value(&mut self, c: Constant) -> Value {
        match c {
            Constant::Bool(b) => Value::Bool(b),
            Constant::Int(i) => Value::Int(i),
            Constant::Float(f) => Value::Float(f),
            Constant::Unit => Value::Unit,
            Constant::String(s) => {
                let h = self.vm.heap.alloc(Object::String(s));
                Value::Obj(h)
            },
            Constant::Function(f) => {
                let closure = Closure {
                    function: *f,
                    upvalues: Vec::new(),
                };

                let h = self.vm.heap.alloc(Object::Closure(closure));
                Value::Obj(h)
            },

            Constant::SharedMemory(sm) => {
                let h = self.vm.heap.alloc(Object::SharedBuffer(sm));
                Value::Obj(h)
            },
            Constant::Socket(s) => {
                let h = self.vm.heap.alloc(Object::Socket(s));
                Value::Obj(h)
            },
            Constant::Listener(l) => {
                let h = self.vm.heap.alloc(Object::Listener(l));
                Value::Obj(h)
            },
        }
    }
}
